// Generated by CoffeeScript 1.3.3
var $, json0, json1, json_dir, log;

$ = jQuery;

json_dir = '/assets/citeplasm/javascripts';

json0 = "" + json_dir + "/demo_initial_data.json";

json1 = "" + json_dir + "/demo_graph_data.json";

log = function(msg, error) {
  if (error == null) {
    error = false;
  }
  if (error) {
    return $.error(msg);
  } else {
    return console.log(msg);
  }
};

$(document).ready(function() {
  var $graph, $wizard, wizardDefinition;
  log("Loading demo...");
  $wizard = $('.wizard');
  $graph = $('.graph');
  wizardDefinition = {
    panes: {
      whatisagraph: {
        "do": function() {
          $graph.graphDemo({
            initial_data: json0
          });
          return $graph.graphDemo('start');
        },
        undo: function() {
          return log('Unable to remove nodes. NYI.', true);
        }
      },
      webofdocs: {
        "do": function() {
          return $graph.graphDemo('add', json1);
        },
        undo: function() {
          return log('Unable to remove nodes. NYI.', true);
        }
      },
      linked: {
        "do": function() {
          if (!$graph.hasClass('linked')) {
            return $graph.graphDemo('toggleState', 'linked');
          }
        },
        undo: function() {
          return $graph.graphDemo('toggleState', 'linked');
        }
      }
    }
  };
  $wizard.wizard(wizardDefinition);
  return $wizard.wizard(wizardDefinition);
});
