// Generated by CoffeeScript 1.3.3
var $;

$ = jQuery;

$(document).ready(function() {
  var $wizard, wizardDefinition;
  console.log("Loading demo...");
  $wizard = $('.wizard');
  wizardDefinition = {
    panes: {
      unlinked: {
        name: "Unlinked",
        "do": function() {
          console.log("Doing unlinked...");
          return true;
        },
        undo: function() {
          console.log("Undoing unlinked...");
          return true;
        }
      }
    }
  };
  return $wizard.wizard(wizardDefinition);
});
